#!/usr/bin/env bash

if [ -z "$PS1" ]; then
  echo -e "${COLOR_RED}You should source this, not run it, for example: source ./link${COLOR_NC}"
else

  link (){
    if [ -e $1 ]; then
      if [ -e $2 ]; then
        rm $2
      fi

      ln -s $1 $2
    fi
  }

  # bash
  link ~/src/dotfiles/etc/bash_profile ~/.bash_profile
  link ~/src/dotfiles/etc/bashrc ~/.bashrc
  link ~/src/dotfiles/etc/bashrc_help ~/.bashrc_help
  link ~/src/dotfiles/etc/bashrc_envs ~/.bashrc_envs

  # git
  link ~/src/dotfiles/etc/gitconfig ~/.gitconfig
  link ~/src/dotfiles/etc/gitignore ~/.gitignore
  link ~/src/dotfiles/etc/gitattributes ~/.gitattributes

  # misc
  link ~/src/dotfiles/etc/subversion ~/.subversion
  link ~/src/dotfiles/etc/autotest ~/.autotest
  link ~/src/dotfiles/etc/irbrc ~/.irbrc
  link ~/src/dotfiles/etc/ssh_config ~/.ssh/config

  source ~/.bash_profile
fi

